"""initial migrations

Revision ID: d276348aaa59
Revises: 534a0261cc63
Create Date: 2019-02-22 20:18:05.441522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd276348aaa59'
down_revision = '534a0261cc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blogs_topic', sa.String(), nullable=True))
    op.drop_column('blogs', 'blogs_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blogs_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'blogs_topic')
    # ### end Alembic commands ###
